foreach(required_env
    SOLARIS_SYSROOT
    SOLARIS_C_COMPILER_WRAPPER
    SOLARIS_CXX_COMPILER_WRAPPER
    SOLARIS_AR
    SOLARIS_RANLIB
    SOLARIS_STRIP)
  if("$ENV{${required_env}}" STREQUAL "")
    message(FATAL_ERROR "${required_env} is required; evaluate cross/env.sh")
  endif()
endforeach()

set(CMAKE_SYSTEM_NAME SunOS)
set(CMAKE_SYSTEM_VERSION 5.11)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSROOT "$ENV{SOLARIS_SYSROOT}")

set(CMAKE_C_COMPILER "$ENV{SOLARIS_C_COMPILER_WRAPPER}")
set(CMAKE_CXX_COMPILER "$ENV{SOLARIS_CXX_COMPILER_WRAPPER}")
set(CMAKE_ASM_COMPILER "$ENV{SOLARIS_C_COMPILER_WRAPPER}")
set(CMAKE_AR "$ENV{SOLARIS_AR}")
set(CMAKE_RANLIB "$ENV{SOLARIS_RANLIB}")
set(CMAKE_STRIP "$ENV{SOLARIS_STRIP}")

# Solaris libc exports many functions with protected visibility. CMake's
# address-taking symbol checks need PIC when linked by LLD.
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_C_FLAGS_INIT "-fPIC")
set(CMAKE_CXX_FLAGS_INIT "-fPIC")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-pthread")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-pthread")

set(CMAKE_FIND_ROOT_PATH "$ENV{SOLARIS_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
